version: "3.8"

services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Automatically initialize tables and notify trigger on launch
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

volumes:
  pgdata:
